version: '3'

services:

  nginx:
    image: nginx:1.13
    volumes:
      - ".:/app"
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8080:80"

  php:
    build: "."
    env_file: 
      - .env
    volumes: 
      - ".:/app"

  mysql:
    image: mysql:5.7
    env_file: 
      - .env
    volumes:
      - "mysql:/var/lib/mysql"

volumes: 
  mysql: