"""empty message

Revision ID: 5e2f77734b9e
Revises: f0c670d0e951
Create Date: 2020-08-31 12:31:43.021114

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e2f77734b9e'
down_revision = 'f0c670d0e951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replies')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'comments', ['reply_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reply_id')

    op.create_table('replies',
    sa.Column('replied_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('replier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['replied_id'], ['comments.id'], name='replies_replied_id_fkey'),
    sa.ForeignKeyConstraint(['replier_id'], ['comments.id'], name='replies_replier_id_fkey'),
    sa.PrimaryKeyConstraint('replied_id', 'replier_id', name='replies_pkey')
    )
    # ### end Alembic commands ###
