"""empty message

Revision ID: 7cbab6ee4da0
Revises: a553caaba213
Create Date: 2020-08-31 02:50:15.134635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cbab6ee4da0'
down_revision = 'a553caaba213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thumbnails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'videos', ['video_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thumbnails', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('video_id')

    # ### end Alembic commands ###
