"""empty message

Revision ID: ba8283fe526a
Revises: 7cbab6ee4da0
Create Date: 2020-08-31 08:15:12.713488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba8283fe526a'
down_revision = '7cbab6ee4da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('comments_comment_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'comments', ['reply_id'], ['id'])
        batch_op.drop_column('comment_id')

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscribed_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('subscriptions_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['subscribed_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('subscriptions_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('subscribed_id')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('comments_comment_id_fkey', 'comments', ['comment_id'], ['id'])
        batch_op.drop_column('reply_id')

    # ### end Alembic commands ###
