"""empty message

Revision ID: f0c670d0e951
Revises: ba8283fe526a
Create Date: 2020-08-31 12:00:36.317035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c670d0e951'
down_revision = 'ba8283fe526a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replies',
    sa.Column('replied_id', sa.Integer(), nullable=False),
    sa.Column('replier_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['replied_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['replier_id'], ['comments.id'], ),
    sa.PrimaryKeyConstraint('replied_id', 'replier_id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('comments_reply_id_fkey', type_='foreignkey')
        batch_op.drop_column('reply_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('comments_reply_id_fkey', 'comments', ['reply_id'], ['id'])

    op.drop_table('replies')
    # ### end Alembic commands ###
